# Generated by Django 5.1 on 2024-09-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stocks',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sentiment', models.DecimalField(decimal_places=10, max_digits=13)),
                ('date_last_accessed', models.DateField(auto_now=True)),
            ],
        ),
    ]
